name = "a9-ms"
main = "worker.js"
compatibility_date = "2024-12-01"

# 静态文件托管（Wrangler v4 assets）
assets = { directory = "./public" }

# 业务数据 KV
[[kv_namespaces]]
binding = "A9_MS_KV"
id = "9a8d80ff38dc488bba9854dac5de74ee"

# 用户账号 KV
[[kv_namespaces]]
binding = "A9_MS_USERS"
id = "668b2c23e4b84bcd99b818f796336fc0"

# 会话 KV
[[kv_namespaces]]
binding = "A9_MS_SESSIONS"
id = "b69c8158dc98483b8eaadbef34006827"

# 定时唤醒，减少冷启动
[triggers]
crons = ["*/5 * * * *"]
