name = "a9-ms-worker"
main = "worker.js"
compatibility_date = "2026-05-14"
account_id = "035ed3a922810717e2265dcbc8fd321b"
workers_dev = true

site = { bucket = "./public" }

[[kv_namespaces]]
binding = "A9_MS_KV"
id = "9a8d80ff38dc488bba9854dac5de74ee"
